name: Lint

on:
  push:
    branches:
      - release
    paths:
      - '**/*.js'
      - '**/*.ts'
  pull_request:
    branches:
      - release
    paths:
      - '**/*.js'
      - '**/*.ts'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Try to fix Linting
        run: npm run lint:fix

      - name: Run ESLint
        run: npm run lint
